### ISSUE TITLE
Request: Before initialization of <DataSort />

### ISSUE THREAD

**Issue by jncolvin** [Corjen/react-data-sort#2]
Hello @Corjen. 

I hope you're well. I first wanted to thank you for creating this awesome library. I'm trying it on one of my projects and find it quite useful. I do have a small request for it.

Would it be possible to implement some kind of `beforeLoad` callback on the <Datasort /> component itself? I'm finding it is attempting to load, before my data is fully populated in my mobx store. Because of this, the `pages` internal state is set to `0` because it thinks there's no data to paginate when there really is. 

What are your thoughts on this?

**Comment by Corjen** [comment]
Hi @jncolvin!

That's so nice to hear, thanks! 😄 

It don't really understand your problem though, could you not wait with rendering DataSort until your mobx data is loaded? E.g. what would the beforeLoad callback do?

Something like:

```
class Something extends Component {

  render() {
    const { loading, data } = this.props // Props from mobx store
    if(loading && !data.length) {
      return <div>Loading...</div>
    }
    return <DataSort data={data}>// Render data</DataSort>
  }
}
```

**Comment by jncolvin** [comment]
@Corjen,

Thanks for your reply and suggestion. I'll admit, I'm still new to the dev scene and often over-think concepts. 

My main issue what that I was clearing my store data in the component life-cycle using `componentWillUnmount`. This was an effort to avoid any residual outdated data. Because I did this, the Datasort `pages` state essentially reset back to 0 the next time my component mounted. Albeit my data was still populated and pagination worked, the page count was non-existant. 

Either way, I believe I got this worked out. Appreciate you chiming in as quick as you did. Please forgive my ignorance.
