### ISSUE TITLE
Question/Bug: searchQuery Matching

### ISSUE THREAD

**Issue by jncolvin** [Corjen/react-data-sort#3]
@Corjen, Can you elaborate on how the search functionality works? Does it do any kind of regex on the objects within the array data? 

Currently, when I pass a searchQuery string, it's searching my objects for what seems to be random. If the letters making up my string exist in any of the objects, it returns those "matching" objects. It'd be nice if the search logic was based on regex for the string so only truly matching are returned. 

If I'm missing something or am completely crazy, please let me know. :)

**Comment by Corjen** [comment]
Good question! Is see I forgot to add the `searchInKeys` props to the docs 🙈Will add that asap.

The `searchInKeys` prop lets you define what keys you want search in. So say you have a data array like this:
```
[
  { id: 1, username: "Corjen"},
  { id: 2, username: "Harry1"},
]
```
Then if you define the `searchInKeys` prop like this `<DataSort searchInKeys={['username]} />` and do a search for `1`, the only data that should be returned is the second row as only the `username` key is searched and only `Harry1` matches.

It uses [match-sorter](https://github.com/kentcdodds/match-sorter) under the hood btw.

This will only be performant for smaller datasets of course as all rendering is done on the client.

**Comment by jncolvin** [comment]
Hi @Corjen,

Thanks for your reply! This is very helpful information. Nice to be able to define an array of fields to match against. That said, I did try to use the `searchInKeys` prop with one example key to match against.

![screen shot 2018-05-10 at 7 32 44 am](https://user-images.githubusercontent.com/9312413/39867824-d174a606-5424-11e8-8677-7bea1e233558.png)

Once I do though, I'm greeted by the following error in my console. 

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at DataSort.render (index.esm.js?3909:167)
    at finishClassComponent (react-dom.development.js?cada:7873)
    at updateClassComponent (react-dom.development.js?cada:7850)
    at beginWork (react-dom.development.js?cada:8225)
    at performUnitOfWork (react-dom.development.js?cada:10224)
    at workLoop (react-dom.development.js?cada:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:581)
    at invokeGuardedCallback (react-dom.development.js?cada:438)
```

Any ideas why this would be occurring? I know that key exists on each object. The key I'm matching against, `first_name`, is simply a string which shouldn't be an issue.

**Comment by Corjen** [comment]
Hi @jncolvin,

I wasn't able to reproduce your issue unfortunately. Could you provide a gist or codesandbox that reproduces the issue?

**Comment by jncolvin** [comment]
Hey @Corjen. My apologies for my lack of response on this. I got caught up with other parts of the project and needed to move on. I appreciate your replies and help here. If you couldn't reproduce, It's likely not an issue with your library. It's probably something I've done. Thanks again Corjen. I'll let you know how it goes.
