### ISSUE TITLE
Question: sort dates

### ISSUE THREAD

**Issue by Sharan-ram** [Corjen/react-data-sort#4]
@Corjen I'm using this in my current project, i'm not able to sort dates, and when my data is a mixture of upper case and lower case letters, can it be case insensitive?

**Comment by Sharan-ram** [comment]
I handled Dates, for case insensitive thing, i can instead covert everything to proper case

**Comment by Corjen** [comment]
Great! So this is solved? :)

**Comment by Sharan-ram** [comment]
yes, in the data, if the string is date then i return it as it is and while rendering, i format it, n for a normal string, I convert it to proper case while sending it to the data prop itself, awesome package, thanks a lot :)
